adtzlr/felupe

- felupe/mesh.py
fixes #7. Do not sweep, instead modify connectivity and slice nodes for phi=360°.
> Fix mesh.revolve if phi=360°

- felupe/doftools.py
- felupe/element.py
- felupe/field.py
- felupe/forms.py
- felupe/math.py
- felupe/region.py
* consistent usage of region.mesh
* replace some left-over old wordings "elements -> cells"
* math simplifcations (remove _linalginv() )
> Add docstrings plus minor improvements

- felupe/field.py
> add __getitem__ method to Field class

- felupe/__init__.py
- felupe/tools.py
> Add newton rhapson solver

- felupe/field.py
- felupe/tools.py
This pull-request makes the Newton-Rhapson code more universal. Updates #29 and fixes #31
> Enhance newtonrhapson function

- felupe/field.py
- felupe/mesh.py
> Fix revolve if phi < 360

- felupe/doftools.py
- felupe/forms.py
- felupe/solve.py
fix wrong dimension of `dr0` and undefined `u0ext`; see #36
fix different dimensions of field and mesh
part of #36
fix different dimensions of field and mesh
...in numba-versions of assemble(); see #36
> fix different dim. of field and mesh; fix solve() if u0ext=None

- felupe/field.py
- felupe/math.py
- felupe/tools.py
> Add strain function

- felupe/region.py
- felupe/utils.py
- tests/test_axi3d.py
> Fix utils.axito3d

- felupe/doftools.py
- felupe/tools.py
- tests/test_linearelastic.py
...and fix NewtonRhapson; fixes #62 and #61
> Add uniaxial loadcase

- felupe/constitution/ad.py
modify F in order to avoid repeated eigenvalues
fixes #67
> simple fix for ad materials

- felupe/region.py
> fix inv(dXdr)

- felupe/forms.py
- felupe/math.py
- felupe/region.py
- tests/test_math.py
- fix Integralform `grad_v=False, grad_u=True` and `grad_v=True, grad_u=False` (disable parallel versions of forms)
- add cross product of two vectors
- make `region.drdX` and `region.dXdr` public attributes
> Features for stress boundary

- docs/quickstart.md
- felupe/quadrature/_gausslegendre.py
- tests/test_quadrature.py
also add permutation for Gauss-Legendre quadrature (`order=2, dim=3`), see #94
> [Docs] Add tools.project to quickstart example

- README.md
- docs/quickstart.md
- felupe/__init__.py
- felupe/region/__init__.py
- felupe/region/_templates.py
- tests/test_region.py
> Add region templates

- README.md
- felupe/dof/__init__.py
- felupe/dof/_loadcase.py
- tests/test_dof.py
> Add more loadcases

- felupe/tools/_post.py
> obtain dim from field in force

- README.md
- felupe/dof/_boundary.py
- tests/test_dof.py
> Add boundary mask

- README.md
- felupe/math/_tensor.py
- tests/test_math.py
> Fix `math.dot`

- README.md
- felupe/dof/__init__.py
- felupe/dof/_loadcase.py
- tests/test_dof.py
> Add `shear` loadcase

- README.md
- felupe/__init__.py
- felupe/constitution/__init__.py
- felupe/constitution/_wrappers.py
- tests/test_constitution.py
> Add matadi wrapper

- README.md
- felupe/tools/_newton.py
- tests/test_tools.py
> Add verbose option `newtonrhapson`

- README.md
- docs/felupe/global/constitution.rst
- felupe/__init__.py
- felupe/constitution/__init__.py
- felupe/constitution/_models.py
- tests/test_constitution.py
- tests/test_tools.py
> Add linear-elastic plane formulations

- docs/felupe/constitution/constitution.rst
- docs/howto.rst
- docs/howto/meshgen.rst
- docs/howto/rbe2.rst
- felupe/constitution/_models.py
> Docs: Add MPC How-To

- docs/tutorial/gettingstarted.rst
- docs/tutorial/hellofelupe.rst
> fix tutorials

- README.md
- felupe/mesh/_mesh.py
- tests/test_mesh.py
> Add mesh copy

- docs/howto/mixed.rst
- felupe/dof/_tools.py
> Fix offsets

- README.md
- felupe/math/_tensor.py
- tests/test_math.py
> Fix `math.dot()` for two vectors

- README.md
- docs/tutorial/platewithhole.rst
- felupe/_assembly/_base.py
- felupe/constitution/_models.py
- tests/test_constitution.py
> Broadcast `fun` in parallel (numba) integrators

- docs/howto/solvers.rst
- felupe/_assembly/_base.py
- tests/test_form.py
* remove unused parallel integrators
* split numba-acc. functions in order to have clearer functions
* improve doc. on solver usage
> Simplify assembly and improve docs on how to use solvers

- README.md
- felupe/_assembly/_form.py
- tests/test_bilinearform.py
> Add `sym` argument to `Bilinearform.integrate()` and `Bilinearform.assemble()`

- README.md
- felupe/_assembly/_base.py
- felupe/_basis/_basis.py
- felupe/_field/_base.py
- felupe/region/_region.py
- tests/test_tools.py
> Preparations for RegionBoundary

- README.md
- felupe/_assembly/_form.py
> Fix dimensions of value-array in assembly of `BilinearForm`

- README.md
- felupe/math/_tensor.py
> Fix `tovoigt()` helper

- felupe/_field/_fields.py
- felupe/region/_templates.py
- felupe/tools/_newton.py
- tests/test_composite.py
> Fix multiple mixed subfields

- felupe/mechanics/_solidbody_tensor.py
- tests/test_mechanics_tensor.py
> Enhance SolidBodyTensor: Automatic init of statevars

- README.md
- felupe/tools/_newton.py
> Fix verbose of newton

- README.md
- felupe/tools/_newton.py
> Check function residuals norm in newton

- felupe/mechanics/_helpers.py
- felupe/mechanics/_solidbody_tensor.py
- felupe/tools/_newton.py
> Fix update of state variables in Newton-Rhapson

- felupe/__init__.py
- felupe/_field/_container.py
- felupe/_field/_fields.py
- felupe/mechanics/__init__.py
- felupe/mechanics/_helpers.py
- felupe/mechanics/_multipoint.py
- felupe/mechanics/_solidbody_gravity.py
- felupe/mechanics/_solidbody_pressure.py
- felupe/mechanics/_solidbody_tensor.py
- felupe/mesh/__init__.py
- felupe/mesh/_tools.py
- felupe/region/_templates.py
- felupe/tools/_newton.py
- tests/test_composite.py
- tests/test_field.py
- tests/test_form.py
- tests/test_mechanics.py
- tests/test_mechanics_tensor.py
- tests/test_mesh.py
- tests/test_mpc.py
- tests/test_readme.py
- tests/test_tools.py
> Add Mesh-tool `mesh.runouts()`

- felupe/mechanics/_solidbody_gravity.py
> Multiply force vector of gravity by -1

- README.md
- felupe/mesh/_tools.py
- tests/test_mesh.py
> Fix `mesh.revolve(axis=1)`

- README.md
- felupe/mechanics/_curve.py
- felupe/mechanics/_step.py
- felupe/mesh/_tools.py
- tests/test_job.py
- tests/test_mesh.py
> Add `callback` argument to `CharacteristicCurve()`

- README.md
- felupe/_assembly/_base.py
- felupe/_basis/_basis.py
- felupe/constitution/_kinematics.py
- felupe/math/_tensor.py
> Remove Warning if `einsumt` is not installed

- CHANGELOG.md
- felupe/element/_lagrange.py
> Add points attribute to lagrange element

- CHANGELOG.md
- felupe/mechanics/_job.py
- felupe/mechanics/_solidbody_incompressible.py
- felupe/tools/_newton.py
> Fix missing update of `x0` in `job.evaluate(x0)` after each completed substep

- CHANGELOG.md
- felupe/mechanics/_solidbody_incompressible.py
- pyproject.toml
- setup.cfg
- tests/test_mechanics.py
> Fix incompressible solid: Wrong volume evaluation for axisymmetric fields

- CHANGELOG.md
- felupe/_field/_container.py
- felupe/constitution/_models_linear_elasticity.py
- tests/test_field.py
- tests/test_planestrain.py
> FieldContainer: Change attribute `values` to method `values()`

- CHANGELOG.md
- felupe/dof/_loadcase.py
> Enhance `dof.shear(compression=(0, 0)`

- CHANGELOG.md
- felupe/__init__.py
- felupe/constitution/__init__.py
- felupe/constitution/_user_materials.py
- felupe/math/__init__.py
- pyproject.toml
- setup.cfg
- tests/test_constitution.py
> Add `UserMaterialHyperelastic()`

- CHANGELOG.md
- felupe/constitution/__init__.py
- felupe/constitution/_user_materials.py
- felupe/constitution/_user_materials_hyperelastic.py
- felupe/math/__init__.py
- pyproject.toml
- setup.cfg
> Make `tensortrax` optional

- CHANGELOG.md
- felupe/constitution/__init__.py
- felupe/constitution/_models_hyperelasticity_ad.py
- tests/test_constitution.py
this includes
and hence, closes #368
> Add more hyperelastic material formulations

- CHANGELOG.md
- felupe/__init__.py
- felupe/_field/_fields.py
- felupe/element/__init__.py
- felupe/element/_quad.py
- felupe/region/__init__.py
- felupe/region/_templates.py
- tests/test_element.py
- tests/test_region.py
also enhance `FieldsMixed()` to support more common kinds of mixed elements
> Add `QuadraticQuad()` and `BiQuadraticQuad()` elements

- CHANGELOG.md
- src/felupe/_field/_base.py
- tests/test_field.py
> Perform reshape and broadcasting if user-defined `Field`-values with correct size are given.

- CHANGELOG.md
- src/felupe/mechanics/_job.py
> `Job`: Append point- and cell-data to default instead of replacing them

- CHANGELOG.md
- src/felupe/_field/_fields.py
> Add a custom mesh for the dual regions in `FieldsMixed(mesh=None)`

- CHANGELOG.md
- src/felupe/_field/_fields.py
- src/felupe/mesh/_mesh.py
- src/felupe/region/_templates.py
- tests/test_field.py
- tests/test_mesh.py
closes #397 
closes #398 
closes #399
> Enhance `FieldsMixed()`: Add support for `RegionLagrange` (family of Taylor-Hood elements)

- CHANGELOG.md
- src/felupe/mechanics/_step.py
- tests/test_job.py
which is useful for linear-elastic solutions
fixes #404
> `Step`: Make arguments `ramp` and `boundaries` optional

- src/felupe/_assembly/_base.py
- src/felupe/_basis/_basis.py
- src/felupe/constitution/_kinematics.py
- src/felupe/math/_tensor.py
some missing changes in import statements, see #407
> Enforce `einsumt`

- .github/workflows/coverage.yml
- CHANGELOG.md
- README.md
- docs/index.rst
- pyproject.toml
- src/felupe/mechanics/_multipoint.py
fixes #410 
fixes #411 
Add support for Python 3.11
> Vectorize implementation of `MultiPointConstraint`

- CHANGELOG.md
- src/felupe/__init__.py
- src/felupe/element/_quad.py
- src/felupe/region/__init__.py
- src/felupe/region/_boundary.py
- src/felupe/region/_templates.py
- tests/test_region.py
this implements `RegionQuadraticQuadBoundary` and `RegionBiQuadraticQuadBoundary`
closes #413
> Add boundary regions for quadratic quads

- CHANGELOG.md
- src/felupe/__init__.py
- src/felupe/region/__init__.py
- src/felupe/region/_boundary.py
- src/felupe/region/_templates.py
- tests/test_region.py
this implements `RegionQuadraticHexahedronBoundary` and `RegionTriQuadraticHexahedronBoundary`
closes #413
> Add boundary regions for quadratic hexahedrons

- CHANGELOG.md
- src/felupe/mechanics/_multipoint.py
- src/felupe/mesh/__init__.py
- src/felupe/mesh/_mesh.py
- src/felupe/mesh/_tools.py
- src/felupe/region/_region.py
- tests/test_mesh.py
- tests/test_mpc.py
> Fix `MultiPointConstraint` and `MultiPointContact` with active skips

- CHANGELOG.md
- src/felupe/mechanics/_job.py
- tests/test_job.py
> Add `Job.evaluate(parallel=False)`

- CHANGELOG.md
- src/felupe/mesh/__init__.py
- src/felupe/mesh/_mesh.py
- src/felupe/mesh/_tools.py
- tests/test_mesh.py
like concatenate, but take `points` from first mesh and don't apply offsets to `cells`. Also add a method for the translation of mesh points.
closes #442 
closes #444
> Add `mesh.stack(meshes)` and `mesh.translate(move, axis)`

- .flake8
- src/felupe/constitution/_models_hyperelasticity_ad.py
- src/felupe/constitution/_models_linear_elasticity.py
- src/felupe/constitution/_user_materials_models.py
- src/felupe/mesh/_convert.py
- src/felupe/mesh/_tools.py
- src/felupe/region/_boundary.py
> Flake8: Remove E741 from ignore list

- CHANGELOG.md
- src/felupe/__init__.py
- src/felupe/tools/__init__.py
- src/felupe/tools/_plot.py
- tests/test_plot.py
> Add `ViewMesh(mesh, cell_type=None)`

- CHANGELOG.md
- src/felupe/constitution/_user_materials_hyperelastic.py
- src/felupe/tools/_plot.py
> Enhance `View`: Add optional point- and cell-data to `ViewMesh`

- CHANGELOG.md
- src/felupe/__init__.py
- src/felupe/tools/__init__.py
- src/felupe/tools/_plot.py
- tests/test_plot.py
> Add `ViewSolid(field, solid=None)` and set `View = ViewSolid`

- CHANGELOG.md
- src/felupe/_assembly/__init__.py
remove imports of: 
- BilinearForm
- BilinearFormMixed
- LinearForm
- LinearFormMixed
- IntegralFormAxisymmetric
- WeakForm
> Remove unused imports of the assembly submodule

- CHANGELOG.md
- docs/examples/enginemount.rst
- docs/examples/shear.rst
- docs/howto/composite.rst
- docs/howto/rbe2.rst
- src/felupe/mesh/_discrete_geometry.py
- src/felupe/region/_boundary.py
- tests/test_composite.py
- tests/test_field.py
- tests/test_mesh.py
- tests/test_mpc.py
and make the cells argument also optional, changes
```python
Mesh.update(cells, cell_type=None)`
```
to
```python
Mesh.update(points=None, cells=None, cell_type=None)`
```
closes #522
> Update-method of `Mesh`: Add optional points-argument

- CHANGELOG.md
- src/felupe/dof/_loadcase.py
- tests/test_dof.py
by user-defined axes.
closes #530
> Enhance uniaxial- and shear-loadcases

- CHANGELOG.md
- src/felupe/_field/_container.py
- src/felupe/mesh/_mesh.py
- tests/test_field.py
> Add `ViewField(field)` as method to `FieldContainer.view()`

- CHANGELOG.md
- src/felupe/dof/_loadcase.py
> Fix `dof.shear(sym=True)`

- CHANGELOG.md
- src/felupe/dof/_boundary.py
> Add `Boundary.apply_mask()`

- CHANGELOG.md
- src/felupe/mesh/_convert.py
- src/felupe/region/_templates.py
> Add argument and change default `RegionTriangleMINI(bubble_multiplier=0.1)`, also for `RegionTetraMINI`

- CHANGELOG.md
- src/felupe/constitution/_models_hyperelasticity.py
- src/felupe/constitution/_user_materials_models.py
- src/felupe/math/_tensor.py
- tests/test_constitution.py
also slightly enhance code-formatting in `NeoHooke.hessian()`.
> Don't broadcast `math.identity() and add optional kwargs in `math.einsum(**kwargs)`

- CHANGELOG.md
- src/felupe/quadrature/__init__.py
- src/felupe/quadrature/_gausslegendre.py
- src/felupe/quadrature/_tetra.py
- src/felupe/quadrature/_triangle.py
- src/felupe/region/_region.py
this fixes #581 
if mesh-points are modified **after** the region is created. Use `region.reload(mesh)` to update the region.
```python
mesh = fem.Cube(n=11)
field = fem.FieldsMixed(region, n=1)
boundaries, loadcase = fem.dof.uniaxial(field, axis=0, sym=False, clamped=True)
mesh.update(points=mesh.rotate(angle_deg=-90, axis=2).points)
region.reload(mesh)
```
> Add `Region.reload(mesh=None, element=None, quadrature=None)`

- CHANGELOG.md
- src/felupe/mesh/_tools.py
this enhances the performance of `Rectangle(n=(k, l))` for `l >> k`, same applies for `Cube`.
> Vectorize `mesh.expand()`

- CHANGELOG.md
- src/felupe/mechanics/_job.py
> Fix logarithmic strain tensor evaluation

- CHANGELOG.md
- src/felupe/math/_tensor.py
> Enhance performance of `cdya()` and pass kwargs in `dot()`

- src/felupe/field/_axi.py
- src/felupe/field/_base.py
- src/felupe/field/_container.py
- src/felupe/field/_planestrain.py
- src/felupe/math/_tensor.py
this should be further used in the solid body classes to improve performance.
> Add output location for `field.extract(out=None)`

- CHANGELOG.md
- src/felupe/assembly/_axi.py
- src/felupe/assembly/_cartesian.py
- src/felupe/assembly/_integral.py
- src/felupe/field/_axi.py
- src/felupe/field/_container.py
- src/felupe/field/_planestrain.py
- src/felupe/mechanics/_helpers.py
- src/felupe/mechanics/_solidbody.py
- src/felupe/mechanics/_solidbody_incompressible.py
- tests/test_mechanics.py
this should increase performance
> Add `out`-locations to the integral forms and use them in the solid bodies

- CHANGELOG.md
- src/felupe/tools/_plot.py
should be invoked manually instead.
> Do not invoke `pyvista.start_xvfb()` on a posix-os

- CHANGELOG.md
- src/felupe/mechanics/_job.py
from `None = Job.evaluate()` to `job = Job.evaluate()`
> Change return value in `job = Job.evaluate()`

- CHANGELOG.md
- src/felupe/tools/_save.py
- tests/test_tools.py
also add a docstring along with an example.
> Rename `tools.save()`-argument `r` to `forces`

- src/felupe/mechanics/_curve.py
- src/felupe/mechanics/_job.py
- tests/test_job.py
and obtain the figure from `ax.get_figure()` instead.
> Remove `fig`-argument in `CharacteristicCurve.plot(ax=None)`

- CHANGELOG.md
- docs/felupe/mesh.rst
- docs/howto/meshgen.rst
- src/felupe/__init__.py
- src/felupe/mechanics/_job.py
- src/felupe/mesh/__init__.py
- src/felupe/mesh/_geometry.py
- src/felupe/mesh/_mesh.py
- src/felupe/mesh/_tools.py
- tests/test_mesh.py
and enhance `mesh.expand()` for vertex -> line meshes
> Add `mesh.Point(a=0)`

- CHANGELOG.md
- src/felupe/field/_base.py
- tests/test_field.py
`Field(region).as_container()` which is equal to `FieldContainer(fields=[Field(region)])`.
> Add `Field.as_container()`

- CHANGELOG.md
- src/felupe/mesh/_mesh.py
- src/felupe/mesh/_read.py
```python
mesh = fem.Rectangle(n=3)
mesh.write(filename="mesh.vtk")
```
> Rename `Mesh.save()` to `Mesh.write()` and add `Mesh.save()` as an alias of it

- CHANGELOG.md
- src/felupe/__init__.py
- src/felupe/field/__init__.py
- src/felupe/field/_dual.py
- src/felupe/field/_fields.py
- tests/test_field.py
> Add `FieldDual` for the dual (secondary) fields in mixed fields

- CHANGELOG.md
- src/felupe/__init__.py
- src/felupe/quadrature/__init__.py
- src/felupe/quadrature/_sphere.py
- tests/test_quadrature.py
> Add quadrature scheme `BazantOh()`

- CHANGELOG.md
- src/felupe/assembly/_integral.py
> Add support for `FieldDual` in `IntegralForm`

- CHANGELOG.md
- src/felupe/math/_tensor.py
- tests/test_math.py
> Fix `math.inv(A)` for `A.shape[:2] == (1, 1)`

- CHANGELOG.md
- src/felupe/mesh/_discrete_geometry.py
- tests/test_mesh.py
to access the columns of the points-array
closes #647
> Add `DiscreteGeometry` properties `x`, `y` and `z`

- CHANGELOG.md
- src/felupe/mesh/_container.py
- src/felupe/mesh/_tools.py
- tests/test_mesh.py
> Add `MeshContainer.stack()`

- CHANGELOG.md
- src/felupe/field/_container.py
- src/felupe/mechanics/_solidbody.py
- src/felupe/mesh/_container.py
pass the `dpi`-argument to matplotlib
> Enhance `imshow()`-methods of solid, field and mesh

- CHANGELOG.md
- src/felupe/tools/_plot.py
> Enhance `Scene.plot()`: Hide internal edges of quadratic celltypes

- CHANGELOG.md
- src/felupe/mechanics/_solidbody.py
- src/felupe/tools/_plot.py
- src/felupe/tools/_project.py
- tests/test_plot.py
where `project` is a callable, e.g. `felupe.tools.project`.
> Add optional projection of stresses in `SolidBody.plot(project=None)`

- CHANGELOG.md
- examples/ex08_shear.py
- src/felupe/mechanics/_multipoint.py
- tests/test_mpc.py
to plot the lines of a multi-point constraint.
> Add `MultiPointConstraint.plot(**kwargs)`

- src/felupe/element/_base.py
- src/felupe/quadrature/_gausslegendre.py
- src/felupe/quadrature/_scheme.py
- src/felupe/quadrature/_tetra.py
- src/felupe/quadrature/_triangle.py
- src/felupe/region/_region.py
> Enhance plots of quadrature schemes

- docs/felupe/assembly.rst
Fix small typo cartesion -> cartesian.
> Fix small typo cartesion -> cartesian

- CHANGELOG.md
- src/felupe/mechanics/_item.py
- tests/test_readme.py
closes #795 
```python
from felupe.math import ddot
mesh = fem.Cube(n=4)
boundaries = fem.dof.symmetry(field[0])
solid = fem.SolidBody(umat=fem.NeoHookeCompressible(mu=1, lmbda=2), field=field)
face = fem.Field(fem.RegionHexahedronBoundary(mesh, mask=mesh.x == 1), dim=3)
right = fem.FieldContainer([face])
@fem.Form(v=right)
def linearform():
def L(v, value, multiplier):
u = right.extract(grad=False)[0]
uext = value * np.array([1, 0, 0]).reshape(3, 1, 1)
return multiplier * ddot(v, u - uext)
return [L]
@fem.Form(v=right, u=right)
def bilinearform():
return [lambda v, u, value, multiplier: multiplier * ddot(v, u)]
values = fem.math.linsteps([0, 1], num=5)
move = …
```
> Add `FormItem().update(values)`

- CHANGELOG.md
- src/felupe/__init__.py
- src/felupe/tools/__init__.py
- src/felupe/tools/_hello_world.py
- tests/test_tools.py
> Add `hello_world()`

- src/felupe/quadrature/_gausslegendre.py
use only the public API of other submodules, see #822.
> Enhance the imports of the `quadrature` submodule

- src/felupe/mechanics/_job.py
> Enhance the imports of the `mechanics` submodule

- src/felupe/assembly/_cartesian.py
- src/felupe/assembly/_integral.py
- tests/test_region.py
to ensure maximum performance.
see also #827 and #828
> Test if region attribute arrays are C-contiguous

- CHANGELOG.md
- src/felupe/mesh/_container.py
- tests/test_mesh.py
> Add `MeshContainer.from_unstructured_grid()`

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement-suggestion.md
This PR adds issue templates for bug reports and enhancement suggestions according to `CONTRIBUTING.md`. Questions should be asked in discussions (no change).
See #853 and #854
> Update issue templates

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/index.rst
This PR closes #853 and is related to the basic checks for the pyOpenSci submission, see https://github.com/pyOpenSci/software-submission/issues/212.
> Fix pyOpenSci basic checks

- docs/conf.py
- docs/felupe/constitution/jax.rst
- docs/tutorial/examples/extut03_building_blocks.py
- src/felupe/constitution/autodiff/jax/__init__.py
- src/felupe/constitution/autodiff/jax/_material.py
- src/felupe/constitution/autodiff/jax/_tools.py
- src/felupe/constitution/autodiff/tensortrax/_hyperelastic.py
- src/felupe/constitution/autodiff/tensortrax/_material.py
- tests/test_constitution_jax.py
as an alternative for `MaterialAD` (`felupe.constitution.autodiff.tensortrax.Material`).
> Add `felupe.constitution.autodiff.jax.Material`

- docs/felupe/constitution/autodiff/jax.rst
- src/felupe/constitution/jax/models/hyperelastic/__init__.py
- src/felupe/constitution/jax/models/hyperelastic/_miehe_goektepe_lulei.py
- src/felupe/constitution/jax/models/hyperelastic/microsphere/__init__.py
- src/felupe/constitution/jax/models/hyperelastic/microsphere/_chain.py
- src/felupe/constitution/jax/models/hyperelastic/microsphere/_framework_affine.py
- src/felupe/constitution/jax/models/hyperelastic/microsphere/_framework_nonaffine.py
- src/felupe/constitution/tensortrax/models/hyperelastic/_miehe_goektepe_lulei.py
- tests/test_constitution_jax.py
along with the Microsphere-framework (affine/non-affine)
> Add `miehe_goektepe_lulei` model for JAX

- docs/felupe/constitution/tools.rst
- src/felupe/constitution/__init__.py
- src/felupe/constitution/linear_elasticity/__init__.py
- src/felupe/constitution/linear_elasticity/_lame_converter.py
- src/felupe/constitution/linear_elasticity/_linear_elastic_orthotropic.py
- src/felupe/constitution/tensortrax/models/hyperelastic/_saint_venant_kirchhoff_orthotropic.py
- tests/test_constitution.py
This PR adds a converter for the Lame parameters for orthotropic materials.
> Add `constitution.lame_converter_orthotropic()`

- src/felupe/constitution/tensortrax/models/hyperelastic/__init__.py
- src/felupe/constitution/tensortrax/models/hyperelastic/_saint_venant_kirchhoff.py
- src/felupe/constitution/tensortrax/models/hyperelastic/_saint_venant_kirchhoff_orthotropic.py
- tests/test_constitution.py
This PR enhances the St. Venant Kirchhoff material formulations by the family of Seth-Hill strains.
> Add an optional strain exponent for the SVK-material

- src/felupe/mechanics/_pointload.py
- tests/test_mechanics.py
This PR adds a plot-method to the point load class.
> Add `PointLoad.plot()`

- CHANGELOG.md
- src/felupe/tools/_hello_world.py
> Fix `hello_word(planestrain=True)`

- CHANGELOG.md
- pyproject.toml
This fixes #953. Change the declaration of the license and license file. See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files
> Update license in pyproject.toml

- docs/howto/composite.rst
Fix typo from seperated to separated.
> Fix typo from seperated to separated
