adtzlr/felupe

- felupe/field.py
- felupe/forms.py
As discussed in #6, now the following is possible:
```python
import felupe as fe
import felupe.math as fm
mesh  = fe.mesh.Rectangle(a=(0,0.5), b=(1,1.5), n=11)
mesh0 = fe.mesh.convert(mesh)
element0 = fe.element.Quad0()
element1 = fe.element.Quad1()
quadrature = fe.quadrature.GaussLegendre(order=1, dim=2)
region0 = fe.Region(mesh0, element0, quadrature)
region  = fe.Region(mesh,  element1, quadrature)
dA = region.dV
displacement = fe.FieldAxisymmetric(region, dim=2)
pressure     = fe.Field(region0, dim=1)
volumeratio  = fe.Field(region0, dim=1, values=1)
fields = (displacement, pressure, volumeratio)
f1 = lambda x: np.isclose(x, 1)
boundaries = fe.doftools.symmetry(displacement)
boundaries["right"] = fe.Boundary(displacement, fx=f1, skip=(1, 0, 0))
boundaries["move" ] = …
```
> Fix Axisymmetry with mixed-field formulations

- felupe/mesh.py
- felupe/quadrature.py
This pull request fixes mesh connectivities (cell orientations) for tet meshes and adds quadrature rules for triangles and tetrahedrons (linear/quadratic). 
sample code snippet using meshzoo:
```python
import felupe as fe
import meshzoo
#%% 3D Tetrahedron
nodes, connectivity = fe.mesh.fix(meshzoo.cube_tetra((0,0,0), (1,1,1), n=5))
mesh = fe.mesh.Mesh(nodes, connectivity, etype="tetra")
element = fe.element.Tet1()
quadrature = fe.quadrature.LinearTetrahedron()
region = fe.Region(mesh, element, quadrature)
dV = region.dV
V = dV.sum()
#%% 2D Triangle
nodes, connectivity = meshzoo.rectangle_tri((0,0), (1,1), n=15)
mesh = fe.mesh.Mesh(nodes, connectivity, etype="triangle")
element = fe.element.Tri1()
quadrature = fe.quadrature.LinearTriangle()
region = fe.Region(mesh, element, quadrature)
dV = …
```
> Fix mesh connectivity (cell orientation) for tet meshes and add quadrature rules for triangles and tetrahedrons

- docs/examples.md
- docs/guide.md
- docs/mesh.md
- docs/quickstart.md
- felupe/element.py
- felupe/mesh.py
- felupe/utils.py
- scripts/script_performance_neohooke.py
- scripts/script_performance_poisson.py
- scripts/script_readme.py
* **IMPORTANT** includes new element class namings; fixes #40 - docs and scripts also updated.
* hexahedrons can be converted to hexahedron20 or hexahedron27, and so on... e.g. `fe.mesh.convert(mesh, oder=2, calc_midfaces=True, calc_midvolumes=True`) converts a `hexahedron` mesh to a `hexahedron27` mesh.
> Enhance mesh.convert capabilities: convert to order=0 and order=2

- felupe/element.py
- felupe/quadrature.py
initial support with
```python
import felupe as fe
import felupe.math as fm
import meshzoo
points, cells = fe.mesh.fix(*meshzoo.cube_tetra((0,0,0), (1,1,1), 7), "tetra")
points_mini = np.zeros((len(cells), points.shape[1]))
cells_mini = np.arange(len(cells)).reshape(-1,1) + len(points)
points_ = np.vstack((points, points_mini))
cells_ = np.hstack((cells, cells_mini))
mesh0 = fe.mesh.Mesh(points, cells, cell_type="tetra")
mesh = fe.mesh.Mesh(points_, cells_, cell_type="tetra")
element0 = fe.element.Tetra()
element = fe.element.TetraMINI()
quadrature = fe.quadrature.CubicTetrahedron()
region0 = fe.Region(mesh0, element0, quadrature)
region = fe.Region(mesh, element, quadrature)
```
> Add MINI element

- felupe/constitution/models.py
- felupe/tools.py
- tests/test_tools.py
> Fix linearelastic

- felupe/mesh/_mesh.py
- felupe/tools/_project.py
- tests/test_mesh.py
Wasn't merged in v.1.3.0. 
fixes #118
> rename mesh.as_discontinous() to mesh.disconnect()

- README.md
- felupe/tools/_newton.py
- tests/test_tools.py
fixes #138 in order to use a linear elastic material in combination with `newtonrhapson`.
> `newtonrhapson`: add kwargs of `field.extract()` for default `fun` and `jac`

- docs/tutorial/gettingstarted.rst
because default value of `sym=True`
> tovoigt is called automatically by felupe.topoints

- README.md
- docs/felupe/global/quadrature.rst
- docs/felupe/global/region.rst
- docs/index.rst
- felupe/__init__.py
- felupe/_assembly/_base.py
- felupe/quadrature/__init__.py
- felupe/quadrature/_gausslegendre.py
- felupe/region/__init__.py
- felupe/region/_boundary.py
- felupe/region/_region.py
- felupe/region/_templates.py
- tests/test_mesh.py
- tests/test_quadrature.py
- tests/test_region.py
- tests/test_tools.py
Introduce a Region class for Boundaries, optionally only on the outline of the model and in combination with a point mask.
Fixes #168  for Quad and Hexahedron.
> Add a region on the boundary faces/edges on a mesh

- README.md
- felupe/constitution/_kinematics.py
- tests/test_constitution.py
- tests/test_region.py
This will simplify the calculation of a pressure boundary.
> Improve AreaChange

- felupe/_assembly/_axi.py
- felupe/_field/_axi.py
- felupe/_field/_fields.py
- felupe/quadrature/_gausslegendre.py
- felupe/region/_boundary.py
- felupe/region/_templates.py
- tests/test_form.py
- tests/test_quadrature.py
- tests/test_region.py
Also fix wrong are normal of boundary regions.
Fixes #200
> Add `axisymmetric` argument to `FieldsMixed`

- README.md
- docs/felupe/global/region.rst
- docs/felupe/mesh/mesh.rst
- felupe/mesh/__init__.py
- felupe/mesh/_tools.py
- tests/test_mesh.py
Convert a Quad or a Hexahedron mesh to a Triangle or a Tetra mesh.
Fixes #201
> Add Mesh-Tool: `triangulate()`

- README.md
- felupe/mesh/_mesh.py
- felupe/mesh/_tools.py
- tests/test_mesh.py
- tox.ini
add attributes `Mesh.as_meshio()` ~and `Mesh.draw()`~, enhance `Mesh.save()`
> Improve Mesh

- README.md
- felupe/__init__.py
- felupe/_assembly/__init__.py
- felupe/_assembly/_base.py
- felupe/_assembly/_form.py
- felupe/_field/_axi.py
- felupe/_field/_base.py
- felupe/element/_triangle.py
- felupe/math/__init__.py
- felupe/mesh/_convert.py
- felupe/mesh/_tools.py
- felupe/region/_boundary.py
- felupe/tools/_save.py
- tests/test_bilinearform.py
- tests/test_form.py
introduce a new function decorator `@Form()`:
```python
from felupe.math import ddot
mesh = fem.mesh.triangulate(fem.Rectangle(n=6))
region = fem.RegionTriangle(mesh)
field = fem.Field(region)
coords = fem.Field(
region, dim=mesh.dim, values=mesh.points
).interpolate()
@fem.Form(v=field, u=field, grad_v=True, grad_u=True)
def a(dv, du):
return ddot(dv, du)
@fem.Form(v=field)
def L(v, coords):
x, y = coords
f = np.sin(np.pi * x) * np.sin(np.pi * y)
return f * v
L.assemble(v=field, kwargs={"coords": coords})
a.assemble(v=field, u=field)
```
fixes #207
> Add function decorator for weakforms

- README.md
- felupe/_assembly/_base.py
- felupe/_assembly/_form.py
- felupe/_basis/_basis.py
- felupe/_field/_axi.py
- felupe/_field/_base.py
- felupe/element/_triangle.py
- felupe/mesh/_convert.py
- felupe/mesh/_tools.py
- felupe/region/_boundary.py
- felupe/tools/_save.py
- tests/test_basis.py
- tests/test_bilinearform.py
- tests/test_form.py
also add parallel Form argument
fixes #211
> Enhance Basis: Parallel evaluation

- README.md
- felupe/math/_tensor.py
- felupe/mechanics/_helpers.py
- felupe/mechanics/_solidbody.py
- tests/test_math.py
- tests/test_mechanics.py
workaround for #220
fixes #222
> Add SolidBody kirchhoff stress

- README.md
- felupe/tools/_newton.py
- tests/test_tools.py
This adds support for any solid body (e.g. `SolidBody`, `SolidBodyTensor` or `SolidBodyPressure`) with `body.assemble.vector()` and `body.assemble.matrix()` methods.
fixes #225
> Enhance `newtonrhapson()`: Add `body` argument

- README.md
- felupe/mechanics/_solidbody_pressure.py
- felupe/tools/_newton.py
- tests/test_mechanics.py
- tests/test_tools.py
Allow multiple bodies to be passed to the Newton-Rhapson algorithm. Take care of SolidBodyPressure
> Newton-Rhapson: Remove `body` and add `bodies` argument

- docs/tutorial/shear.rst
- felupe/tools/_post.py
- tests/test_tools.py
fixes #234 
also removes `offsets` arguments from `tools.force()` and `tools.moment()` and use `field.offsets` instead.
> Docs: Fix tutorial "shear"

- README.md
- docs/howto/composite.rst
- docs/tutorial/hellofelupe.rst
- docs/tutorial/platewithhole.rst
- felupe/dof/_loadcase.py
- tests/test_dof.py
- tests/test_tools.py
> Improve loadcase

- README.md
- felupe/_assembly/_base.py
- felupe/_assembly/_mixed.py
- felupe/_field/__init__.py
- felupe/_field/_fields.py
- felupe/_field/_planestrain.py
- tests/test_planestrain.py
fixes #256 
Example usage:
```python
m = fem.Rectangle(n=6)
r = fem.RegionQuad(m)
f = fem.FieldsMixed(r, n=3, planestrain=True)
u = fem.ThreeFieldVariation(fem.NeoHooke(mu=1, bulk=5000))
b = fem.SolidBody(u, f)
loadcase = fem.dof.uniaxial(f, clamped=True)[-1]
res = fem.newtonrhapson(items=[b], **loadcase)
```
> Add `FieldPlaneStrain`

- felupe/_assembly/_base.py
- felupe/mechanics/_solidbody_tensor.py
- tests/test_mechanics_tensor.py
> Field Integration: Fix field-trimming for plane strain

- README.md
- felupe/__init__.py
- felupe/mechanics/__init__.py
- felupe/mechanics/_pointload.py
- felupe/mechanics/_solidbody_gravity.py
- tests/test_mechanics.py
- tests/test_mechanics_tensor.py
> Add PointLoad

- felupe/__init__.py
> Add missing import `FieldPlaneStrain`

- felupe/tools/__init__.py
Can be used for numeric continuation
> Import `fun_items()` and `jac_items()` from `felupe.tools._newton`

- README.md
- felupe/_assembly/_axi.py
- felupe/constitution/_mixed.py
- felupe/constitution/_models.py
- felupe/element/_lagrange.py
- felupe/mesh/__init__.py
- felupe/mesh/_geometry.py
- felupe/mesh/_tools.py
- tests/test_job.py
- tests/test_mesh.py
> Add `mesh.Grid(*xi)` and `mesh.concatenate([mesh1, mesh2, ...])`

- README.md
- felupe/mechanics/_step.py
- tests/test_job.py
For more than one solid body in `items=[body1, body2, ...]` it is necessary to use a global `field`, which must be passed as `job.evaluate(x0=field)`.
fixes #285
> Add `job.evaluate(x0=field)`

- CHANGELOG.md
- felupe/region/_boundary.py
> Fix ignored surface mask for `cells_faces` of `RegionBoundary`

- CHANGELOG.md
- felupe/__init__.py
- felupe/mesh/__init__.py
- felupe/mesh/_container.py
- felupe/mesh/_mesh.py
- felupe/region/_boundary.py
- tests/test_mesh.py
Similar to a field container, but which operates on a list of meshes (with identical dimensions of the point arrays). This should simplify the definition of meshes/regions/fields with more than one solid body.
fixes #310
fixes #311
> Add `MeshContainer` and string-representation for `Mesh` objects

- CHANGELOG.md
- felupe/mechanics/_job.py
- felupe/mesh/_container.py
- tests/test_mesh.py
This enables a new readme example:
```python
mesh = fem.MeshContainer([
fem.Cube(n=11), # elastic-block
fem.Cube(a=(1, 0, 0), b=(1.1, 1, 1), n=(2, 11, 11)), # end-plate
], merge=True) # merge duplicate points
regions = [fem.RegionHexahedron(m) for m in mesh]
block = fem.FieldsMixed(regions[0], n=3, values=(0, 0, 1))
plate = fem.FieldContainer([fem.Field(regions[1], dim=3)])
boundaries = fem.dof.uniaxial(block, right=1.1, clamped=True)[0]
neo_hooke = fem.ThreeFieldVariation(fem.NeoHooke(mu=1, bulk=5000))
linear_elastic = fem.LinearElastic(E=21000, nu=0.3)
rubber = fem.SolidBody(umat=neo_hooke, field=block)
steel = fem.SolidBody(umat=linear_elastic, field=plate)
move = fem.math.linsteps([0, 1, -0.2, 0], num=10)
step = fem.Step(
items=[rubber, steel], …
```
> Enhance Mesh-Container

- CHANGELOG.md
- felupe/mechanics/_job.py
- tests/test_job.py
fixes #319. Before, the cell connectivity is mixed up if a global field `x0` is given. Hence, displacement/strain output was wrong.
> `job.evaluate(x0=...)`: Take mesh from global field `x0` if present

- CHANGELOG.md
- felupe/__init__.py
- felupe/constitution/_models.py
- felupe/mechanics/__init__.py
- felupe/mechanics/_solidbody_incompressible.py
- tests/test_constitution.py
- tests/test_mechanics.py
The basic idea evolved out of #296 in combination with the **Mean-Dilatation** technique, see e.g. [Bonet & Wood](https://www.cambridge.org/core/books/nonlinear-continuum-mechanics-for-finite-element-analysis/67AD6DBAAB77E755C09E7FB82565DA0B). Due to a static-condensation of the internal (secondary) fields, this is not as general but considerably (more than 3x) faster than the three-field formulation on global mixed-fields. Usage will be basically
```python
mesh = fem.Cube(n=6)
field = fem.FieldsMixed(region, n=1)
umat = fem.NeoHooke(mu=1)
solid = fem.SolidBodyNearlyIncompressible(umat, field, bulk=5000)
boundaries, lc = fem.dof.uniaxial(field, move=-0.1, clamped=True)
res = fem.newtonrhapson(items=[solid], **lc)
```
and is equal to
```python
mesh = …
```
> Add `SolidBodyNearlyIncompressible(umat, field, bulk)`

- CHANGELOG.md
- felupe/tools/_project.py
- tests/test_tools.py
This enables support for triangles and tetrahedrons in `project()`.
fixes #328 as discussed in #322, derived by the idea of @ZAARAOUI999
Project the cell mean-values to mesh-points.
Computes the weighted average by using the quadrature weights.
> Add `project(mean=True)`

- CHANGELOG.md
- docs/tutorial/beam.rst
- felupe/constitution/_models_linear_elasticity.py
- tests/test_constitution.py
- tests/test_mechanics.py
because `einsumt>=0.9.3` supports broadcasting, see https://github.com/mrkwjc/einsumt/pull/2.
This saves both
a) memory and
b) computation time.
> Do not broadcast linear-elastic elasticity tensor

- CHANGELOG.md
- felupe/math/_math.py
- tests/test_math.py
add `linsteps(points=[0, 5, 0], num=[5, 10])`
fixes #351
> Enhance `linsteps` by supporting a list of substeps

- CHANGELOG.md
- felupe/constitution/__init__.py
- felupe/constitution/_models_hyperelasticity_ad.py
- pyproject.toml
- setup.cfg
- tests/test_constitution.py
all based on the isochoric-volumetric split of the deformation gradient.
> Add models for isotropic hyperelasticity `UserMaterialHyperelastic()`

- CHANGELOG.md
- src/felupe/dof/_loadcase.py
- tests/test_dof.py
> Change loadcases: Detect Min/Max Coordinates of `mesh.points`

- CHANGELOG.md
- src/felupe/mesh/_mesh.py
- tests/test_mesh.py
This includes:
...and the following code-block will be possible:
```python
region = fem.RegionTriQuadraticHexahedron(mesh)
mesh_dual = mesh.disconnect(points_per_cell=8, calc_points=False)
field = fem.FieldsMixed(region, n=3, mesh=mesh_dual)
```
closes #402
> Enhance `Mesh.disconnect(points_per_cell=None, calc_points=True)`

- CHANGELOG.md
- src/felupe/mesh/_tools.py
for `z` and `phi`. They failed if they were of type `np.int32`. The check is changed and now uses `np.isscalar()`.
fixes #420
> Fix scalar-checks in `mesh.expand()` and `mesh.revolve()`

- CHANGELOG.md
- src/felupe/mesh/_convert.py
- src/felupe/mesh/_discrete_geometry.py
- src/felupe/mesh/_helpers.py
- src/felupe/mesh/_mesh.py
- src/felupe/mesh/_tools.py
- tests/test_mesh.py
closes #424
This enables
```python
fem.Rectangle(n=5).expand(n=4, z=1)
```
in addition to the still useful but sometimes very lengthy code
```python
rect = fem.Rectangle(n=5)
cube = fem.mesh.expand(rect, n=4, z=1)
```
> Enhance `Mesh`: Mesh tools as methods

- CHANGELOG.md
- README.md
- docs/index.rst
- pyproject.toml
- src/felupe/_assembly/_base.py
- src/felupe/_basis/_basis.py
- src/felupe/constitution/_kinematics.py
- src/felupe/math/_tensor.py
- tox.ini
fixes #445 (JupyterLite import fails)
> Threaded einsum: Fall-back to numpy if `einsumt` is not available

- src/felupe/tools/_newton.py
> Fix timings in `newtonrhapson()`

- CHANGELOG.md
- README.md
- docs/examples/platewithhole.rst
- src/felupe/mechanics/_job.py
- src/felupe/tools/_plot.py
- tests/test_plot.py
from `fun(substep)` to `fun(field, substep=None)`
also rename `Result.plot()` argument `cpos` to `view` and change default view.
> `Job.evaluate()`: Change point- and cell-data function arguments

- src/felupe/tools/_plot.py
- tests/test_plot.py
If `name=None`, the `show_edges` argument is applied on the undeformed mesh.
> `Result.plot(name=None)`: Plot only the undeformed mesh

- CHANGELOG.md
- README.md
- docs/index.rst
- pyproject.toml
- src/felupe/mechanics/_job.py
- tests/test_job.py
- tox.ini
using `tqdm` but fallback to old output if module not installed. Old output is recovered by `Job.evaluate(verbose=2)`.
closes #468
> `Job`: Add progress bar

- docs/examples/platewithhole.ipynb
- src/felupe/__init__.py
- src/felupe/mechanics/_job.py
- src/felupe/tools/__init__.py
- src/felupe/tools/_misc.py
- src/felupe/tools/_plot.py
> `Job.evaluate(verbose=True)`: Further reduce the output

- CHANGELOG.md
- src/felupe/math/_math.py
- src/felupe/mechanics/_solidbody_gravity.py
- tests/test_math.py
> Multi-column `math.linsteps(axis=None, axes=None)` and optional args in `SolidBodyGravity(field, gravity=None, density=1.0)`

- CHANGELOG.md
- src/felupe/tools/_plot.py
and always show a transparent undeformed mesh. In `ViewMesh`, this results in two identical mesh plots. If it makes problems, change that in the future.
closes #480
> Warp the mesh for `View.plot(name=None)`

- src/felupe/_basis/_basis.py
`q` for quadrature-points
was missed in #489, see #487
> `Basis`: Rename idx in `einsum()`

- CHANGELOG.md
- docs/howto/axi.rst
- src/felupe/__init__.py
- src/felupe/_assembly/__init__.py
- src/felupe/_assembly/_axi.py
- src/felupe/_assembly/_form.py
- src/felupe/_assembly/_integral.py
- src/felupe/_assembly/_weak.py
- src/felupe/mechanics/_helpers.py
- src/felupe/mechanics/_solidbody.py
- src/felupe/mechanics/_solidbody_gravity.py
- src/felupe/mechanics/_solidbody_incompressible.py
- src/felupe/mechanics/_solidbody_pressure.py
- src/felupe/tools/_newton.py
Rename internal `IntegralFormMixed` to `IntegralForm`, which is now consistent internally and in the top-level namespace. The previous internal base-class for a single-field `IntegralForm` is renamed to `WeakForm`.
> Rename internal `IntegralFormMixed` to `IntegralForm`

- CHANGELOG.md
- src/felupe/tools/_plot.py
> Don't modify a given label in `Scene.plot(label=None)`

- CHANGELOG.md
- src/felupe/mechanics/_curve.py
- tests/test_job.py
- Don't plot x- and y-labels if they are not specified.
- Add a transposed plot: Switch/Flip x- and y-axes in the plot.
> Enhance plotting in a characteristic-curve job

- CHANGELOG.md
- src/felupe/constitution/_models_hyperelasticity_ad.py
by fixing the implementation of the second invariant.
closes #501
> Fix `mooney_rivlin()`, `third_order_deformation()` and `van_der_waals()`

- CHANGELOG.md
- src/felupe/mesh/_tools.py
> Fix `mesh.concatenate()` for a list of length one

- CHANGELOG.md
- src/felupe/_field/_fields.py
- src/felupe/mesh/_convert.py
- src/felupe/mesh/_mesh.py
don't disconnect the dual mesh.
**Description**: *Fix nearly-incompressible hyperelasticity on (bubble-enriched MINI) triangle/tetrahedrons*.
Fixes #537 
```python
import pypardiso
mesh = fem.Cube(n=4).triangulate().add_midpoints_volumes(cell_type="tetra")
region = fem.RegionTetraMINI(mesh)
field = fem.FieldsMixed(region, n=3)
umat = fem.ThreeFieldVariation(fem.NeoHooke(mu=1, bulk=5000))
solid = fem.SolidBody(umat, field)
move = fem.math.linsteps([0, 1], num=21)
step = fem.Step(items=[solid], ramp={boundaries["move"]: move}, boundaries=boundaries)
job = fem.CharacteristicCurve(steps=[step], boundary=boundaries["move"])
job.evaluate(tol=1e-3, solver=pypardiso.spsolve)
fig, ax = job.plot(
xlabel="Displacement …
```
> Fix `FieldsMixed()` for MINI-elements

- CHANGELOG.md
- src/felupe/_field/_fields.py
User-given keyword-arguments will overwrite the hardcoded values for `grad` and `quadrature`.
> `FieldsMixed(region, **kwargs)`: Merge `kwargs` for the dual region

- .github/workflows/coverage.yml
- CHANGELOG.md
- README.md
- docs/index.rst
- pyproject.toml
- src/felupe/__about__.py
- src/felupe/constitution/_user_materials.py
- src/felupe/math/_tensor.py
- src/felupe/tools/_newton.py
- src/felupe/tools/_project.py
- tox.ini
> Add support for Python 3.12

- CHANGELOG.md
- docs/felupe/assembly.rst
- src/felupe/__init__.py
- src/felupe/assembly/expression/_decorator.py
- src/felupe/assembly/expression/_expression.py
- src/felupe/mechanics/__init__.py
- src/felupe/mechanics/_item.py
- tests/test_readme.py
closes #563 
The readme example with a form expression for linear elasticity:
```python
mesh = fem.Cube(n=11)
from felupe.math import ddot, sym, trace
@fem.Form(v=field, u=field, grad_v=[True], grad_u=[True])
def bilinearform():
def a(gradv, gradu, μ=1.0, λ=2.0):
δε, ε = sym(gradv), sym(gradu)
return 2 * μ * ddot(δε, ε) + λ * trace(δε) * trace(ε)
return [a]
@fem.Form(v=field, grad_v=[True])
def linearform():
def L(gradv, μ=1.0, λ=2.0):
δε = sym(gradv)
ε = field.extract(grad=True, sym=True, add_identity=False)[0]
return 2 * μ * ddot(δε, ε) + λ * trace(δε) * trace(ε)
return [L]
item = fem.FormItem(bilinearform, linearform, sym=True)
step = …
```
> Add `FormItem(bilinearform, linearform=None)`

- CHANGELOG.md
- src/felupe/dof/_boundary.py
- tests/test_dof.py
fixes #572 
also fixes #517 
This will change the default value of the skip-argument `Boundary(skip=None)`.
> `Boundary`: Add support for a dof-based `mask`

- CHANGELOG.md
- README.md
- docs/index.rst
- tox.ini
as they are now available on PyPI for Python 3.12
> VTK-wheels: Remove extra-index-url `https://wheels.vtk.org`

- CHANGELOG.md
- src/felupe/mesh/_discrete_geometry.py
- tests/test_mesh.py
as suggested by @ZAARAOUI999 in https://github.com/adtzlr/felupe/issues/583#issuecomment-1869116553 in #583,
add a `callback`-argument to `Mesh.update()` in order to simplify the reload of an already existing instance of a region.
```python
mesh = fem.Cube(n=11)
field = fem.FieldsMixed(region, n=1)
boundaries, loadcase = fem.dof.uniaxial(field, axis=0, sym=False, clamped=True)
new_points = mesh.rotate(angle_deg=-90, axis=2).points
mesh.update(points=new_points, callback=region.reload)
```
> Add `Mesh.update(callback=None)`

- CHANGELOG.md
- README.md
- src/felupe/mechanics/_job.py
- src/felupe/mechanics/_solidbody.py
- src/felupe/mechanics/_solidbody_incompressible.py
- src/felupe/tools/_plot.py
- tests/test_mechanics.py
Add view-methods for `SolidBody` and `SolidBodyNearlyIncompressible` (same as already implemented for mesh and fields).
> Add view-methods for solid bodies

- CHANGELOG.md
- docs/felupe/tools.rst
- src/felupe/tools/__init__.py
- src/felupe/tools/_newton.py
> Rename `tools._newton.Result` to `tools.NewtonResult`

- CHANGELOG.md
- src/felupe/tools/_post.py
also change the function argument names to more descriptive ones.
fixes #604
> Fix `tools.moment(field, forces, boundary, centerpoint=np.zeros(3))`

- CHANGELOG.md
- src/felupe/mechanics/_job.py
- src/felupe/tools/_newton.py
this enables to view the convergence graph:
for
```python
import matplotlib.pyplot as plt
mesh = fem.Cube(n=6)
boundaries, loadcase = fem.dof.uniaxial(field, clamped=True, move=-0.3)
umat = fem.NeoHooke(mu=1)
solid = fem.SolidBodyNearlyIncompressible(umat, field, bulk=5000)
res = fem.newtonrhapson(items=[solid], **loadcase)
plt.semilogy(res.fnorms, "o-")
plt.xlabel(r"Iteration # $\rightarrow$")
plt.ylabel(r"Norm of function $|f_1| / (\varepsilon + |f_0|)$")
```
norms of the objective function are also saved as `Job.fnorms` (this is a list of lists, one list for each substep).
> Add `tools.NewtonResult(xnorms=None, fnorms=None)`

- CHANGELOG.md
- src/felupe/mesh/_mesh.py
More descriptive variable names, like `point_ids` instead of `points`, also for cells.
- Add new method to `Mesh` for getting point ids next to a given point coordinate `Mesh.get_point_ids(value)`.
- Add new method to `Mesh` for getting cells attached to a given point coordinate `Mesh.get_cell_ids(point_ids)`.
- Add new method to `Mesh` for getting neighbour cells `Mesh.get_cell_ids_neighbours(cell_ids)`.
- Add new method to `Mesh` for getting shared points between neighbour cells `Mesh.get_point_ids_shared(cell_ids_neighbours)`.
- Add new method to `Mesh` for getting points on regular grids which are located at corners `Mesh.get_point_ids_corners()`.
- Add new method to `Mesh` for modifying the cell connectivity at corners `Mesh.modify_corners(point_ids=None)`, supported for regular quad …
> Rename arguments of new `Mesh`-methods

- CHANGELOG.md
- src/felupe/field/_container.py
- src/felupe/mechanics/_solidbody.py
- src/felupe/mesh/_mesh.py
because the newly `ax=None`-argument from v7.14 was inserted before `*args`.
fixes #614
> Fix `Mesh.imshow(ax=None)`, `FieldContainer.imshow(ax=None)` and `SolidBody.imshow(ax=None)`

- CHANGELOG.md
- src/felupe/field/_base.py
- src/felupe/field/_container.py
- tests/test_field.py
```python
mesh = fem.Cube(n=3)
region_dual = fem.RegionConstantHexahedron(mesh.dual(points_per_cell=1))
displacement = fem.Field(region, dim=3)
pressure = fem.Field(region_dual)
field = fem.FieldContainer([displacement, pressure])
field = displacement & pressure
volume_ratio = fem.Field(region_dual)
field_new = field & volume_ratio
field_new_2 = volume_ratio & field
```
> Create `FieldContainer` by all logical-and combinations of `Field` and `FieldContainer`

- CHANGELOG.md
- src/felupe/mesh/_tools.py
fixes #624 (as mentioned in https://github.com/adtzlr/felupe/discussions/622)
```python
from skfem import MeshTet
mesh_skfem = MeshTet().refined(2)
mesh_skfem.save("trialMesh.xdmf")
from meshio import xdmf
meshio_mesh = xdmf.read("trialMesh.xdmf")
mesh = fem.Mesh(
points=meshio_mesh.points,
cells=meshio_mesh.get_cells_type("tetra"),
cell_type=meshio_mesh.cells[0].type,
)
region = fem.RegionTetra(mesh)
mesh = mesh.flip(np.any(region.dV < 0, axis=0))
region.reload(mesh)
assert np.all(region.dV > 0)
region_u = fem.RegionQuadraticTetra(mesh.add_midpoints_edges())
region_p = fem.RegionTetra(
mesh=fem.mesh.dual(mesh, disconnect=False),
quadrature=region_u.quadrature,
grad=False,
)
```
> Fix `Mesh.flip(mask=None)`: Take care of the mask

- CHANGELOG.md
- src/felupe/mechanics/_curve.py
- src/felupe/mechanics/_job.py
- tests/test_job.py
> Add optional kwargs to `Job(callback=lambda i, j, res, **kwargs: None, **kwargs)`

- CHANGELOG.md
- src/felupe/field/_dual.py
- tests/test_field.py
closes #645 
With a connected mesh, the last block of the assembled hessians of `ThreeFieldVariation` is not invertible.
```python
mesh = fem.Cube(n=3).convert(2, 0, 1, 1)
region = fem.RegionTriQuadraticHexahedron(mesh)
field = fem.FieldsMixed(region, n=3, disconnect=False)
umat = fem.ThreeFieldVariation(fem.NeoHooke(mu=1, bulk=5000))
form = fem.IntegralForm(umat.hessian([*field.extract(), None]), field, region.dV, field)
blocks = form.assemble(block=False)
from scipy.sparse.linalg import inv
res = inv(blocks[-1].T)
```
With a disconnected mesh, this is possible (inverses on cell-level).
```python
mesh = fem.Cube(n=3).convert(2, 0, 1, 1)
region = fem.RegionTriQuadraticHexahedron(mesh) …
```
> Add `FieldDual(disconnect=None)`.

- CHANGELOG.md
- src/felupe/constitution/_models_hyperelasticity_ad.py
- src/felupe/constitution/_view.py
- tests/test_constitution.py
This is a fix to support all versions of `tensortrax`.
Also adds support for initial state variables for `ViewMaterial`.
> Use only the official API of `tensortrax.math`

- CHANGELOG.md
- src/felupe/tools/_plot.py
> Only add `off_screen` and `notebook` keyword-arguments to `pyvista.Plotter(**kwargs)` if they are `True`

- CHANGELOG.md
- src/felupe/assembly/expression/_linear.py
- src/felupe/mechanics/_item.py
- tests/test_readme.py
fixes #674 
**Also changed within this PR**
- Don't require a `bilinearform` in `FormItem(bilinearform=None)`. An empty `FormItem` is now a valid item in a `Step`. For empty vectors/matrices, the shape is inferred from `sum(FieldContainer.fieldsizes)` instead of `FieldContainer.fields[0].values.size`. closes #676 and closes #677
> Fix error during assembly in `Form` for different mesh- and field-dimensions

- CHANGELOG.md
- examples/ex10_poisson-equation.py
- examples/ex11_notch-stress.py
- src/felupe/assembly/expression/_basis.py
- src/felupe/assembly/expression/_bilinear.py
- src/felupe/assembly/expression/_decorator.py
- src/felupe/assembly/expression/_expression.py
- src/felupe/assembly/expression/_linear.py
- src/felupe/assembly/expression/_mixed.py
- src/felupe/math/_field.py
- src/felupe/mechanics/_item.py
- src/felupe/tools/_project.py
- tests/test_basis.py
- tests/test_bilinearform.py
- tests/test_readme.py
closes #679 
However, the arguments are still supported - they may be still passed within the `**kwargs`. However, they have no effect on the bases passed to the weakform-callables. The weakform must be changed from
```python
from felupe.math import ddot, sym, trace
@fem.Form(v=field, u=field, grad_v=[True], grad_u=[True], kwargs={"mu": 1.0, "lmbda": 2.0})
def bilinearform():
"A container for a bilinear form."
def linear_elasticity(gradv, gradu, mu, lmbda):
de, e = sym(gradv), sym(gradu)
return 2 * mu * ddot(de, e) + lmbda * trace(de) * trace(e)
return [linear_elasticity]
```
to
```python
from felupe.math import ddot, sym, trace, grad
@fem.Form(v=field, u=field, kwargs={"mu": 1.0, "lmbda": 2.0})
def bilinearform():
"A container for a bilinear form."
def linear_elasticity(v, u, mu, lmbda): …
```
> Simplify `Form`: Remove required `grad_v` and `grad_u` args and obtain the gradient by `v.grad` or `grad(v)`

- CHANGELOG.md
- src/felupe/tools/_project.py
- tests/test_tools.py
Throw errors if the (quadrature of the) region is not suitable for projection for triangle/tetra elements.
For further details see #690
> Fall-back to `tools.extrapolate(mean=True)` for `project(mean=True)`

- CHANGELOG.md
- src/felupe/mesh/_container.py
- src/felupe/mesh/_mesh.py
- src/felupe/mesh/_tools.py
- tests/test_mesh.py
this fixes #695 
and fixes #696 
and fixes #698
> Fix single-layer `mesh.expand(n=1)` and add axis of expansion `mesh.expand(axis=-1)`

- CHANGELOG.md
- src/felupe/element/_lagrange.py
- src/felupe/mesh/_geometry.py
- src/felupe/quadrature/_gausslegendre.py
- src/felupe/region/_templates.py
- tests/test_region.py
closes #701 
```python
import pyvista as pv
cube = fem.mesh.CubeArbitraryOrderHexahedron(order=5)
region = fem.RegionLagrange(cube, order=5, dim=3)
cube.plot(opacity=0.9).show()
boundaries, loadcase = fem.dof.uniaxial(field, clamped=True, move=-0.3)
solid = fem.SolidBody(umat=fem.NeoHooke(mu=1, bulk=5), field=field)
step = fem.Step(items=[solid], boundaries=boundaries)
job = fem.Job(steps=[step]).evaluate()
surface = field.plot().mesh.separate_cells().extract_surface(nonlinear_subdivision=4)
edges = surface.extract_feature_edges()
plotter = pv.Plotter()
plotter.add_mesh(surface)
plotter.add_mesh(edges, style="wireframe", color="black", line_width=3)
plotter.show()
```
> Make `ArbitraryOrderLagrangeElement` VTK-compatible

- CHANGELOG.md
- src/felupe/field/_container.py
- src/felupe/tools/_plot.py
- src/felupe/tools/_project.py
- src/felupe/tools/_save.py
- tests/test_plot.py
- tests/test_readme.py
- tests/test_tools.py
This removes all other arguments from `topoints(values, region)`.
See also #711
> Simplify `tools.topoints(values, region)`

- CHANGELOG.md
- src/felupe/mesh/_mesh.py
- src/felupe/mesh/_tools.py
This allows to generate meshes like
```python
import pypardiso
R = 50
r = 10
N = 3.75
L = 200
details = 4
sections = 80
phi = np.rad2deg(np.arctan(L / (2 * R * np.pi * N)))
area = fem.Circle(n=details, centerpoint=(0, R), radius=r).expand(0).rotate(phi, axis=1)
mesh = area.revolve(int(sections * N), 360 * N, axis=0, expand_dim=False)
p = mesh.points.reshape(int(sections * N), area.npoints, -1)
p[..., 0] += np.linspace(0, L, int(sections * N)).reshape(-1, 1)
mesh.points[:] = p.reshape(*mesh.points.shape)
mesh.update(
points=np.vstack(
[mesh.points, [[mesh.x.min() - 1e-1, 0, 0], [mesh.x.max() + 1e-1, 0, 0]]]
)
)
mesh = mesh.rotate(-90, axis=1)
```
> Enhance `mesh.expand(expand_dim=True)` and `mesh.revolve(expand_dim=True)` 

- examples/ex06_rubber-metal-spring.py
- src/felupe/mechanics/_multipoint.py
- tests/test_mpc.py
where the keyword-arguments are passed to the PyVista Line/Rectangle. By default, the contact plane(s) are plotted as black-transparent rectangles at an optional offset. This offset avoids the flickering of the next cells.
> Add `MultiPointContact.plot(**kwargs)` method

- CHANGELOG.md
- docs/tutorial/examples/README.rst
- docs/tutorial/examples/extut01_getting_started.py
- docs/tutorial/examples/extut02_job.py
- docs/tutorial/examples/extut03_building_blocks.py
- examples/ex01_beam.py
- src/felupe/mechanics/_job.py
- src/felupe/tools/_newton.py
- tests/test_job.py
- tests/test_tools.py
this will show progress bars for `verbose=True` e.g. in the docs when the global verbosity level is deactivated by `FELUPE_VERBOSE = "false"`.
closes #735
> Change default `verbose=None` in `Job.evaluate()` and `newtonrhapson()`

- CHANGELOG.md
- docs/felupe/math.rst
- src/felupe/math/__init__.py
- src/felupe/math/_solve.py
- tests/test_constitution_newton.py
for two-dimensional problems.
See discussion #741.
```python
import tensortrax as tr
from tensortrax.math import trace
from tensortrax.math.linalg import inv
from tensortrax.math.special import dev, from_triu_1d, triu_1d
mesh = fem.Rectangle(n=3)
region = fem.RegionQuad(mesh)
field = fem.FieldContainer([fem.FieldPlaneStrain(region, dim=2)])
@fem.constitution.isochoric_volumetric_split
def finite_strain_viscoelastic_newton(C, Cin, mu, eta, dtime):
"Finite Strain Viscoelastic material formulation."
def evolution(Ci, Cin, C, mu, eta, dtime):
"Viscoelastic evolution equation."
return mu / eta * dev(C @ inv(Ci)) @ Ci - (Ci - Cin) / dtime
Cin = from_triu_1d(Cin, like=C)
Ci = fem.newtonrhapson( …
```
> Add `math.solve_2d(A, b)`

- CHANGELOG.md
- src/felupe/constitution/_view.py
for materials with state variables. The state variables are now correctly handled during the Newton iterations for the transversal stretches.
Fixes #752 
```python
def fun(λ3):
λ2 = λ3
F = eye * np.array([λ1, λ2, λ3]).reshape(1, 3, 1, -1)
if self.statevars_included:
statevars = self.statevars
if statevars is None:
statevars = np.zeros((*self.umat.x[-1].shape, 1, 1))
P = np.zeros_like(F)
for increment, defgrad in enumerate(F.T):
P[..., [increment]], statevars = self.umat.gradient(
[F[..., [increment]], statevars]
)
else:
P, statevars = self.umat.gradient([F, None])
return P[2, 2].ravel()
```
> Fix `MaterialStrain.plot()`

- CHANGELOG.md
- src/felupe/constitution/_view.py
- src/felupe/constitution/hyperelasticity/models/__init__.py
- src/felupe/constitution/hyperelasticity/models/_alexander.py
- tests/test_constitution.py
fixes #760 
This also resolves a minor issue when plotting the keyword-arguments of a constitutive material. For list-based material parameters of length 1, the brackets aren't shown.
> Fix the Alexander model

- CHANGELOG.md
- src/felupe/constitution/_base.py
- tests/test_constitution.py
to optimize the material parameters with relative residuals instead of absolute residuals.
closes #765
> Add `ConstitutiveMaterial.optimize(relative=False)`

- CHANGELOG.md
- docs/felupe/constitution/hyperelasticity.rst
- docs/felupe/constitution/lagrange.rst
- examples/ex13_morph-rubber-wheel.py
- src/felupe/constitution/__init__.py
- src/felupe/constitution/hyperelasticity/models/__init__.py
- src/felupe/constitution/hyperelasticity/models/_morph_representative_directions.py
- src/felupe/constitution/lagrange/models/__init__.py
- src/felupe/constitution/lagrange/models/_morph_representative_directions.py
- src/felupe/constitution/lagrange/models/_morph_uniaxial.py
- src/felupe/constitution/lagrange/models/microsphere/__init__.py
- src/felupe/constitution/lagrange/models/microsphere/_framework_affine.py
- tests/test_constitution.py
This enhances the performance by a more effective automatic differentiation. The old-version for `Hyperelastic` is still available in `constitution.hyperelasticity.models.morph_representative_directions()`.
> Rebase `morph_representative_directions()` as Total-Lagrange material for `MaterialAD`

- CHANGELOG.md
- src/felupe/constitution/_base.py
> Don't update the material parameters in-place and don't convert them to arrays in `ConstitutiveMaterial.optimize()`

- CHANGELOG.md
- examples/ex18_nonlinear-viscoelasticity-newton.py
- src/felupe/math/__init__.py
- src/felupe/math/_solve.py
and rebase `math.solve_2d(A, b)` on `math.solve_nd(A, b, n=2)`. This function also supports batched arrays with zero dimensions (scalars).
> Add `math.solve_nd(A, b, n=1)`

- CHANGELOG.md
- docs/howto/mixed.rst
- src/felupe/assembly/expression/_linear.py
- src/felupe/constitution/hyperelasticity/core/_neo_hooke_nearly_incompressible.py
- src/felupe/field/_axi.py
- src/felupe/field/_base.py
- src/felupe/field/_container.py
- src/felupe/field/_planestrain.py
- src/felupe/math/_tensor.py
- src/felupe/mechanics/_item.py
- src/felupe/region/_region.py
- tests/test_constitution.py
- tests/test_dtype.py
- tests/test_field.py
- tests/test_form.py
- tests/test_tools.py
also for axisymmetric and plane-strain fields.
This PR enables the assembly of single-precision vectors/matrices.
```python
mesh = fem.Cube(n=3)
region = fem.RegionHexahedron(mesh).astype(dtype)
displacement = fem.Field(region, dim=3, dtype=dtype)
field = fem.FieldContainer([displacement])
solid = fem.SolidBody(fem.NeoHooke(mu=1.0, bulk=2.0), field)
job = fem.Job([fem.Step([solid], boundaries=boundaries)]).evaluate(tol=tol)
```
> Add `Region.astype(dtype=None)` and `Field(..., dtype=None)`

- CHANGELOG.md
- docs/felupe/mesh.rst
- src/felupe/mesh/__init__.py
- src/felupe/mesh/_interpolate.py
- tests/test_mesh.py
This enables an interpolation of a line mesh in N-D space, hopefully useful for further progress on #810.
```python
mesh = fem.mesh.Line(n=5).expand(n=1)
t = mesh.x.copy()
mesh.points[:, 0] = np.sin(np.pi / 2 * t)
mesh.points[:, 1] = np.cos(np.pi / 2 * t)
xi = np.linspace(0, 1, 101)
mesh_new = interpolate_line(mesh, xi=xi, axis=1)
ax = mesh_new.imshow(style="points", color="black")
```
> Add `mesh.interpolate_line(mesh, xi, axis)`

- CHANGELOG.md
- src/felupe/mesh/_interpolate.py
- tests/test_mesh.py
This changes `mesh.interpolate_line(line_mesh, xi, axis).points_derivative` from a method to an array.
> Change the derivative storage in `mesh.interpolate_line()`

- CHANGELOG.md
- src/felupe/mechanics/_solidbody.py
- src/felupe/mechanics/_solidbody_incompressible.py
also for `SolidBodyNearlyIncompressible` and for `vector()`.
This PR provides the (optional) `block`-argument of an integral form in the solid-body assemble-methods. If `block=False`, the vector/matrix is not assembled to a block matrix/vector but the list of sub-blocks is assembled instead.
> Add optional `SolidBody.assemble.matrix(block=False)`

- CHANGELOG.md
- docs/howto/solid.rst
- docs/howto/solvers.rst
- src/felupe/field/_base.py
- src/felupe/mechanics/_helpers.py
- src/felupe/mechanics/_pointload.py
- src/felupe/mechanics/_solidbody_force.py
- src/felupe/mechanics/_solidbody_gravity.py
- src/felupe/mechanics/_solidbody_pressure.py
- src/felupe/mesh/_mesh.py
- src/felupe/mesh/_tools.py
- src/felupe/tools/_newton.py
This PR adds a `multiplier=None` attribute to the `Assemble` helper, which is used in solid body items.
See #816 for further details. This changes the sign of the results for
* `SolidBodyForce`,
* `SolidBodyPressure`,
* `SolidBodyGravity` and
* `PointLoad`.
> Add optional `Assemble(multiplier=None)`

- CHANGELOG.md
- docs/felupe/mechanics.rst
- src/felupe/mechanics/__init__.py
- src/felupe/mechanics/_helpers.py
Change the visibility of the internal helpers `Assemble`, `Evaluate` and `Results` of the mechanics-module `felupe.mechanics` from private to public.
> Change the visibility of the helpers in the mechanics-module from private to public

- examples/ex09_numeric-continuation.py
In #817, the assembled vectors and matrices of a point load has a different sign. This is only relevant if `item.assemble.vector()` is called manually. This is the case in Example 09. This PR provides a fix.
closes #819
> Fix Ex.09: Take care of changed sign of external form items

- CHANGELOG.md
- src/felupe/__init__.py
- src/felupe/assembly/_axi.py
- src/felupe/assembly/_cartesian.py
- src/felupe/assembly/_integral.py
- src/felupe/constitution/_view.py
- src/felupe/field/_dual.py
- src/felupe/field/_evaluate.py
use only public API's in imports from other submodules, see #822 for more details. Also add the `assembly` submodule to the global namespace.
closes #822
> Enhance (isolate) the cross-imports between submodules

- CHANGELOG.md
- src/felupe/region/_region.py
due to non-contiguous region attributes.
```python
mesh = fem.Cube(n=21)
```
```
region.dhdX.flags
Out[1]: 
C_CONTIGUOUS : True
F_CONTIGUOUS : False
OWNDATA : True
WRITEABLE : True
ALIGNED : True
WRITEBACKIFCOPY : False
```
closes #827
> Fix the assembly performance

- CHANGELOG.md
- docs/felupe/assembly.rst
- src/felupe/assembly/expression/__init__.py
- src/felupe/assembly/expression/_basis.py
in the `assembly.expression` namespace, also add them to the API docs.
> Make the classes `Basis`, `BasisField` and `BasisArray` public

- CHANGELOG.md
- src/felupe/field/_axi.py
- src/felupe/field/_base.py
- src/felupe/field/_container.py
- src/felupe/field/_planestrain.py
- src/felupe/region/_region.py
closes #857.
```pycon
>>> import felupe as fem
>>> 
>>> mesh = fem.Cube(n=11).triangulate().add_midpoints_volumes(cell_type="tetra")
>>> region = fem.RegionTetraMINI(mesh)
>>> field = fem.FieldsMixed(region, n=3)
>>> 
>>> field.extract()[0].flags
C_CONTIGUOUS : True
F_CONTIGUOUS : False
OWNDATA : True
WRITEABLE : True
ALIGNED : True
WRITEBACKIFCOPY : False
```
> Extract C-contiguous arrays by default from fields

- CHANGELOG.md
- src/felupe/constitution/poisson/_laplace.py
this PR adds an optional multiplier in `Laplace(multiplier=1.0)`.
> Add an optional multiplier in `Laplace(multiplier=1.0)`

- CHANGELOG.md
- src/felupe/mesh/_dual.py
- tests/test_mesh.py
> Fix the number of points for non-disconnected dual-meshes

- CHANGELOG.md
- src/felupe/constitution/_view.py
- tests/test_constitution.py
this raises an error now to avoid the wrong results.
fixes #852
> Fix wrong result of `ConstitutiveMaterial.plot()` if any stretch <= 0

- CHANGELOG.md
- docs/felupe/constitution.rst
- docs/felupe/constitution/jax.rst
- pyproject.toml
- src/felupe/constitution/__init__.py
- src/felupe/constitution/jax/__init__.py
- src/felupe/constitution/jax/_hyperelastic.py
- src/felupe/region/_boundary.py
- tests/test_constitution_jax.py
This PR adds a `Hyperelastic` feature-equivalent `constitution.jax.Hyperelastic`-class which uses JAX instead of tensortrax.
> Add `constitution.jax.Hyperelastic`

- CHANGELOG.md
- src/felupe/constitution/jax/models/hyperelastic/__init__.py
- src/felupe/constitution/jax/models/hyperelastic/_helpers.py
- tests/test_constitution_newton.py
This PR adds the isochoric-volumetric splot decorator for JAX materials. It also includes a new test for hyperelastic materials with an embedded minimization-problem for the evolution of the state variables. The trick is to use `x_without_gradient = jax.lax.stop_gradient(x)`.
> Add `isochoric_volumetric_split()` for JAX-hyperelastic material

- docs/felupe/constitution/autodiff.rst
- docs/felupe/constitution/autodiff/jax.rst
- src/felupe/constitution/jax/_helpers.py
- src/felupe/constitution/jax/_hyperelastic.py
- src/felupe/constitution/jax/_material.py
- tests/test_constitution_jax.py
This makes the Hyperelastic/Material JAX-classes with state variables a bit more unflexible: `-1`-batch axes are not allowed in `pmap` and hence, explicit axes (>0) must be specified. That means scalar-valued state variables must be converted to a length-1 array.
To use multiple cores of a CPU device as local XLA devices:
```python
import os
os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=4"
```
> Enable `jax.Hyperelastic(..., parallel=True)` with `jax.pmap` on quadrature-points axis

- CHANGELOG.md
- examples/ex02_plate-with-hole.py
- examples/ex11_notch-stress.py
- src/felupe/mechanics/_helpers.py
- src/felupe/mechanics/_solidbody.py
- src/felupe/view/_solid.py
- tests/test_mechanics.py
- tests/test_readme.py
If the stress is simply `Stress`, then the first Piola-Kirchhoff stress is exported. This allows to export the default-engineering stress in the examples with linear-elastic materials.
> Add `SolidBody.evaluate.stress()` and autodetect the stress-type in `SolidBody.plot(name)` from `name`

- docs/felupe/mechanics.rst
- src/felupe/__init__.py
- src/felupe/mechanics/__init__.py
- src/felupe/mechanics/_free_vibration.py
- src/felupe/mechanics/_solidbody.py
- src/felupe/mechanics/_solidbody_incompressible.py
- tests/test_free_vibration.py
- tests/test_mechanics.py
with methods to `evaluate()` and `extract()` the n-th eigenvector to a field.
```python
mesh = fem.Rectangle(b=(5, 1), n=(50, 10))
region = fem.RegionQuad(mesh)
field = fem.FieldContainer([fem.FieldPlaneStrain(region, dim=2)])
boundaries = dict(left=fem.Boundary(field[0], fx=0))
solid = fem.SolidBody(umat=fem.LinearElastic(E=2.5, nu=0.25), field=field, density=1.0)
res = fem.FreeVibration(items=[solid], boundaries=boundaries).evaluate()
field, frequency = res.extract(n=4, inplace=True)
ax = solid.imshow("Stress", component=0)
ax.set_title(rf"Frequency $f_5$ = {frequency:.2} Hz")
```
> Add `FreeVibration(items, boundaries)`

- CHANGELOG.md
- src/felupe/dof/_tools.py
- src/felupe/mechanics/_free_vibration.py
- src/felupe/mechanics/_solidbody.py
- src/felupe/tools/_hello_world.py
- tests/test_dof.py
- tests/test_free_vibration.py
This PR closes #911.
Now it's possible to prescribe multiaxial values without manual broadcast+ravel required:
```python
mesh = fem.Cube(n=6)
value = np.array([1.0, 2.0, 3.0])
boundaries = dict(
left=fem.Boundary(field[0], fx=0),
right=fem.Boundary(field[0], fx=1, value=value),
)
dof0, dof1 = fem.dof.partition(field, boundaries)
ext0 = fem.dof.apply(field, boundaries, dof0)
```
> Enhance `Boundary`: Add support for multiaxial prescribed `value`-argument

- CHANGELOG.md
- docs/tutorial/examples/extut03_building_blocks.py
- src/felupe/dof/_boundary.py
- tests/test_dof.py
and fix `Boundary(..., mode="and")` by ignoring any non-given axes.
> Add `Boundary.plot()` and fix `Boundary(..., mode="and")`

- CHANGELOG.md
- docs/felupe/dof.rst
- docs/tutorial/examples/extut03_building_blocks.py
- src/felupe/__init__.py
- src/felupe/dof/__init__.py
- src/felupe/dof/_boundary.py
- src/felupe/dof/_dict.py
- tests/test_dof.py
with methods to plot, screenshot and imshow.
```python
field = fem.Field(
fem.RegionHexahedron(fem.Cube(b=(3, 1, 1), n=5)), dim=3
).as_container()
boundaries = fem.BoundaryDict(
left=fem.Boundary(field[0], fx=0, skip=(0, 0, 1)),
right=fem.Boundary(field[0], name="my_label", fx=3, skip=(0, 1, 0)),
)
plotter = boundaries.plot()
img = boundaries.screenshot()
ax = boundaries.imshow()
```
> Add `BoundaryDict`

- CHANGELOG.md
- examples/ex01_beam.py
- examples/ex02_plate-with-hole.py
- examples/ex03_plasticity.py
- examples/ex05_rubber-metal-bushing.py
- examples/ex07_engine-mount.py
- examples/ex08_shear.py
- src/felupe/dof/_dict.py
- src/felupe/math/_math.py
with default values except for column `axis` if `axis` is not None.
> Enhance `math.linsteps(..., values=0.0)`

- CHANGELOG.md
- src/felupe/field/_container.py
- tests/test_field.py
This PR enhances `FieldContainer.link()`. If no other field is given, all field values of the container are linked to the values of the first field.
> Enhance `FieldContainer.link()`

- CHANGELOG.md
- src/felupe/assembly/_integral.py
- src/felupe/mechanics/_solidbody.py
- tests/test_mechanics.py
to apply a final callable in `SolidBody.assemble.vector()` or `SolidBody.assemble.matrix()`.
> Add `SolidBody(..., block=True, apply=None)`

- src/felupe/constitution/_view.py
See also #931 - this avoids unnecessary figures created in the tests. If non-physical stretches are present, no (empty) figure is created.
> Don't create a figure if error in `umat.plot()`

- CHANGELOG.md
- src/felupe/region/_region.py
- src/felupe/region/_templates.py
- tests/test_region.py
This closes #938. Hopefully useful for things like #936.
```python
>>> import felupe as fem
>>> 
>>> mesh_container = fem.MeshContainer([fem.Rectangle()])
>>> element = fem.Quad()
>>> quadrature = fem.GaussLegendre(order=1, dim=2)
>>> region = fem.Region(mesh_container, element, quadrature)
TypeError: A mesh container is not supported by a region, use a mesh instead.
```
Hopefully this is clear enough to change it to:
```python
>>> import felupe as fem
>>> 
>>> mesh_container = fem.MeshContainer([fem.Rectangle()])
>>> mesh = mesh_container[0]
>>> element = fem.Quad()
>>> quadrature = fem.GaussLegendre(order=1, dim=2)
>>> region = fem.Region(mesh, element, quadrature)
```
> Raise a TypeError if a container is used in a region

- CHANGELOG.md
- src/felupe/__init__.py
- src/felupe/element/__init__.py
- src/felupe/element/_vertex.py
- src/felupe/field/_base.py
- src/felupe/mesh/_container.py
- src/felupe/mesh/_convert.py
- src/felupe/region/__init__.py
- src/felupe/region/_templates.py
- tests/test_element.py
- tests/test_field.py
- tests/test_mesh.py
- tests/test_region.py
This PR adds a method to merge a mesh container into a vertex mesh. This can be used as a top-level mesh when dealing with multiple solid bodies with different element types. This is only useful if the mesh-container has been created with `merge=True`.
closes #937 
```python
container = fem.MeshContainer([fem.Rectangle()], merge=True)
mesh = container.as_vertex_mesh()
region = fem.RegionVertex(mesh)
field = fem.Field(region, dim=2).as_container()  # this is the top-level field
```
A more high-level approach is also available.
```python
container = fem.MeshContainer([fem.Rectangle()], merge=True)
field = fem.Field.from_mesh_container(container).as_container()  # this is the top-level field
```
~Further work for mixed-field solid-bodies is …
> Add `MeshContainer.as_vertex_mesh()` and `Field.from_mesh_container()`

- CHANGELOG.md
- src/felupe/mesh/_interpolate.py
- tests/test_mesh.py
use a curve-progress variable if `axis=None` by default.
```python
>>> import felupe as fem
>>> import numpy as np
>>> from scipy.interpolate import CubicSpline
>>>
>>> mesh = fem.mesh.Line(b=1.0, n=5).expand(n=1)
>>> t = mesh.x.copy()
>>> mesh.points[:, 0] = np.sin(2 * np.pi * t)
>>> mesh.points[:, 1] = np.cos(2 * np.pi * t)
>>>
>>> mesh_new = fem.mesh.interpolate_line(
...     mesh, xi=np.linspace(0, 1), Interpolator=CubicSpline, bc_type="periodic"
... )
>>>
>>> mesh_new.plot(
...     plotter=mesh.plot(style="points", color="red", point_size=15),
...     color="black",
... ).show()
```
> Enhance `mesh.interpolate_line(axis=None)`

- pyproject.toml
Fix the license-files entry. Fixes #952. See #953.
> Make license-files more explicit in `pyproject.toml`

- CHANGELOG.md
- pyproject.toml
by enforcing `setuptools>=77.0.3` for [PEP639](https://peps.python.org/pep-0639/).
This PR also changes the labels of the project-urls to [well-known labels](https://packaging.python.org/en/latest/specifications/well-known-project-urls/#well-known-labels).
Now, `pyproject.toml` follows this [guideline](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/).
See also #953.
> `pyproject.toml` ensure PEP639 support

- src/felupe/__init__.py
- tests/test_mesh.py
which causes the docs not to build because `TriQuadraticHexahedron` is not available in the top-level namespace of felupe. Thanks @tkoyama010! 🎉 
fixes #957 
This is the error of RTD, but this can't be reproduced locally.
```
WARNING: autodoc: failed to import class 'TriQuadraticHexahedron' from module 'felupe'; the following exception was raised:
--
383 | Traceback (most recent call last):
384 | File "/home/docs/checkouts/readthedocs.org/user_builds/felupe/envs/latest/lib/python3.12/site-packages/sphinx/util/inspect.py", line 461, in safe_getattr
385 | return getattr(obj, name, *defargs)
386 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
387 | AttributeError: module 'felupe' has no attribute 'TriQuadraticHexahedron'. Did you mean: 'QuadraticHexahedron'?
```
There's also another error in …
> Fix missing import of `TriQuadraticHexahedron`

- CHANGELOG.md
- docs/conf.py
I think it works without the path, but let's change it according to the offical docs of the PyData theme.
see #957
> Fix the path to the logo in `docs/conf.py`

- CHANGELOG.md
- src/felupe/mesh/_container.py
> Fix a typo in the docstring of `MeshContainer.from_unstructured_grid()`

- CHANGELOG.md
- src/felupe/constitution/_base.py
- src/felupe/constitution/_view.py
- tests/test_constitution.py
fixes #964 
Let's check the stability of the Mooney-Rivlin material model formulation. The stability is evaluated on (valid) principal stretches of a biaxial deformation. Biaxial deformations are only stable up to a longitudinal stretch of 1.35. Similar results are also shown here: https://bentleysystems.service-now.com/community?id=kb_article_view&sysparm_article=KB0115733 but with different material parameters and load cases.
```python
>>> import numpy as np
>>> import felupe as fem
>>> import felupe.constitution.tensortrax as mat
>>>
>>> umat = fem.Hyperelastic(
...     mat.models.hyperelastic.mooney_rivlin,
...     C10=0.25,
...     C01=0.25,
... ) & fem.Volumetric(bulk=5000)
>>> view = umat.view()
>>> λ = view.biaxial()[0]
>>>
>>> F = np.zeros((3, 3, 1, λ[0].size))
>>> for a in …
```
> Add `ConstitutiveMaterial.is_stable()` and fix `CompositeMaterial`

- CHANGELOG.md
- docs/felupe/region.rst
- src/felupe/__init__.py
- src/felupe/mechanics/_truss.py
- src/felupe/region/__init__.py
- src/felupe/region/_templates.py
- tests/test_mechanics.py
This is an addon for #966 
```python
mesh = fem.Mesh(
points=[[0, 0], [1, 1], [2.0, 0]], cells=[[0, 1], [1, 2]], cell_type="line"
)
region = fem.RegionTruss(mesh)
field = fem.Field(region, dim=2).as_container()
boundaries = fem.BoundaryDict(fixed=fem.Boundary(field[0], fy=0))
umat = fem.LinearElastic1D(E=np.ones(2))
truss = fem.Truss(umat, field, area=[2, 2])
load = fem.PointLoad(field, [1])
move = fem.math.linsteps([0, -0.1], num=5, axis=1, axes=2)
step = fem.Step(items=[truss, load], ramp={load: move}, boundaries=boundaries)
job = fem.Job(steps=[step]).evaluate(verbose=2)
mesh.plot(plotter=load.plot(plotter=boundaries.plot()), line_width=5).show()
```
> Add `RegionTruss`

- src/felupe/field/_container.py
- src/felupe/mechanics/__init__.py
- src/felupe/mechanics/_solidbody.py
- src/felupe/mechanics/_solidbody_incompressible.py
- tests/test_mechanics.py
This implementation is based on the idea of #971. The `results`-keyword is not yet implemented - results are always re-evaluated after a checkpoint is restored.
closes #971
> Add `checkpoint()` and `restore()` methods for solid bodies and field containers

- src/felupe/field/_axi.py
- src/felupe/field/_base.py
- src/felupe/field/_container.py
- src/felupe/field/_dual.py
- src/felupe/field/_fields.py
- tests/test_field.py
but only mixed-fields which were created with `FieldsMixed()` are supported. This is because only template regions are supported by `FieldDual`.
> Enhance `FieldContainer.merge()` for `FieldsMixed()`

- docs/index.rst
- tests/test_constitution.py
fixes #991 
When running the tests locally in a new virtual environment, matplotlib tries to import tcl/tk and raises an error because tcl can't be found. This PR enforces matplotlib to use a non-GUI backend in `test_constitution.py`.
Also add a note to the docs on how to install all optional dependencies in editable mode.
> Tests: Enforce `matplotlib.use("Agg")` to avoid tcl-related errors
